# Generated by ariadne-codegen

from io import IOBase

from pydantic import BaseModel as PydanticBaseModel, ConfigDict


class UnsetType:
    def __bool__(self) -> bool:
        return False


UNSET = UnsetType()


class Upload:
    def __init__(self, filename: str, content: IOBase, content_type: str):
        self.filename = filename
        self.content = content
        self.content_type = content_type
